title: "Crystal Slack Invite"
heading: "Crystal Slack"
description: "Slack team for Crystal language"
email: "Your mail address"
helper: "Which address do you receive Slack invitation?"
submit: "Join"
progress: "Sending ..."
succeeded: "Succeeded!"
failed: "Failed!"
